### ISSUE TITLE
Feature Request: `/pin <message link>`

### ISSUE THREAD

**Issue by RhythmicSys** [Peashooter101/JaredVirtualMachine#1]
Imagined functionality: 
Set a pins channel, or it will default to the channel the command is run in
This would create and send a webhook message using
* Author's Icon 
* Author's Name
* Embed with
  * Color of the author's highest role color
  * Message content
  * Timestamp of the original message
  * Button that links to the original message
  * Field that shows the message is a pinned message (or another way to show that the message is a pinned message/webhook message)
  * Possibly a 'Pinned by <user> on <date>' 

Visual example of this

## Original message:
![image](https://user-images.githubusercontent.com/45906780/187773220-abc3dad4-f901-4b4e-b22c-c61ee7c9ef82.png)

## Idea of what a pinned message would look like:
![image](https://user-images.githubusercontent.com/45906780/187772395-7297522f-0a53-475a-bee4-97ac36d3b404.png)

**Comment by Peashooter101** [comment]
# Feature Request Completed!

![Pin Message Feature](https://user-images.githubusercontent.com/20095065/188412158-c4122133-46d4-4d3d-bb19-92fadc9dc4e9.png)
